version: '3.1'

services:
  app:
    container_name: automated_test
    restart: always
    network_mode: "host"
    build:
      context: .
    environment:
      - cmdrun=http
    ports:
      - 10000:10000
    command: ["./app", "http"]
  app-tasks:
    container_name: automated_test-tasks
    restart: always
    network_mode: "host"
    build:
      context: .
    environment:
      - cmdrun=tasks
    command: ["./app", "tasks"]
  psql:
    image: dockerhub.ir/postgres:latest
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
#    ports:
#      - 5432:5432
  influxdb:
    image: dockerhub.ir/influxdb:latest
    container_name: influxdb
    network_mode: "host"
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
      - INFLUXDB_DB=prometheus
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_USER=${INFLUXDB_USER:-prometheus}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-prompass}
  redis:
    image: dockerhub.ir/redis
    restart: always
    network_mode: "host"
#    ports:
#      - 6379:6379