// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accounts            string
	AuthInfo            string
	Datacenters         string
	Drafts              string
	EndpointStats       string
	Endpoints           string
	Faq                 string
	Gateways            string
	NetCats             string
	NetCatsStats        string
	Orders              string
	Packages            string
	PageSpeeds          string
	PageSpeedsStats     string
	Pings               string
	PingsStats          string
	Projects            string
	RelationDatacenters string
	Tickets             string
	TraceRoutes         string
	TraceRoutesStats    string
}{
	Accounts:            "accounts",
	AuthInfo:            "auth_info",
	Datacenters:         "datacenters",
	Drafts:              "drafts",
	EndpointStats:       "endpoint_stats",
	Endpoints:           "endpoints",
	Faq:                 "faq",
	Gateways:            "gateways",
	NetCats:             "net_cats",
	NetCatsStats:        "net_cats_stats",
	Orders:              "orders",
	Packages:            "packages",
	PageSpeeds:          "page_speeds",
	PageSpeedsStats:     "page_speeds_stats",
	Pings:               "pings",
	PingsStats:          "pings_stats",
	Projects:            "projects",
	RelationDatacenters: "relation_datacenters",
	Tickets:             "tickets",
	TraceRoutes:         "trace_routes",
	TraceRoutesStats:    "trace_routes_stats",
}
