// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// PageSpeed is an object representing the database table.
type PageSpeed struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Data      null.JSON `boil:"data" json:"data,omitempty" toml:"data" yaml:"data,omitempty"`
	ProjectID int       `boil:"project_id" json:"project_id" toml:"project_id" yaml:"project_id"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	DeletedAt null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *pageSpeedR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L pageSpeedL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PageSpeedColumns = struct {
	ID        string
	Data      string
	ProjectID string
	UpdatedAt string
	CreatedAt string
	DeletedAt string
}{
	ID:        "id",
	Data:      "data",
	ProjectID: "project_id",
	UpdatedAt: "updated_at",
	CreatedAt: "created_at",
	DeletedAt: "deleted_at",
}

var PageSpeedTableColumns = struct {
	ID        string
	Data      string
	ProjectID string
	UpdatedAt string
	CreatedAt string
	DeletedAt string
}{
	ID:        "page_speeds.id",
	Data:      "page_speeds.data",
	ProjectID: "page_speeds.project_id",
	UpdatedAt: "page_speeds.updated_at",
	CreatedAt: "page_speeds.created_at",
	DeletedAt: "page_speeds.deleted_at",
}

// Generated where

var PageSpeedWhere = struct {
	ID        whereHelperint
	Data      whereHelpernull_JSON
	ProjectID whereHelperint
	UpdatedAt whereHelpertime_Time
	CreatedAt whereHelpertime_Time
	DeletedAt whereHelpernull_Time
}{
	ID:        whereHelperint{field: "\"page_speeds\".\"id\""},
	Data:      whereHelpernull_JSON{field: "\"page_speeds\".\"data\""},
	ProjectID: whereHelperint{field: "\"page_speeds\".\"project_id\""},
	UpdatedAt: whereHelpertime_Time{field: "\"page_speeds\".\"updated_at\""},
	CreatedAt: whereHelpertime_Time{field: "\"page_speeds\".\"created_at\""},
	DeletedAt: whereHelpernull_Time{field: "\"page_speeds\".\"deleted_at\""},
}

// PageSpeedRels is where relationship names are stored.
var PageSpeedRels = struct {
	PagespeedPageSpeedsStats string
}{
	PagespeedPageSpeedsStats: "PagespeedPageSpeedsStats",
}

// pageSpeedR is where relationships are stored.
type pageSpeedR struct {
	PagespeedPageSpeedsStats PageSpeedsStatSlice `boil:"PagespeedPageSpeedsStats" json:"PagespeedPageSpeedsStats" toml:"PagespeedPageSpeedsStats" yaml:"PagespeedPageSpeedsStats"`
}

// NewStruct creates a new relationship struct
func (*pageSpeedR) NewStruct() *pageSpeedR {
	return &pageSpeedR{}
}

func (r *pageSpeedR) GetPagespeedPageSpeedsStats() PageSpeedsStatSlice {
	if r == nil {
		return nil
	}
	return r.PagespeedPageSpeedsStats
}

// pageSpeedL is where Load methods for each relationship are stored.
type pageSpeedL struct{}

var (
	pageSpeedAllColumns            = []string{"id", "data", "project_id", "updated_at", "created_at", "deleted_at"}
	pageSpeedColumnsWithoutDefault = []string{"project_id", "created_at"}
	pageSpeedColumnsWithDefault    = []string{"id", "data", "updated_at", "deleted_at"}
	pageSpeedPrimaryKeyColumns     = []string{"id"}
	pageSpeedGeneratedColumns      = []string{}
)

type (
	// PageSpeedSlice is an alias for a slice of pointers to PageSpeed.
	// This should almost always be used instead of []PageSpeed.
	PageSpeedSlice []*PageSpeed
	// PageSpeedHook is the signature for custom PageSpeed hook methods
	PageSpeedHook func(context.Context, boil.ContextExecutor, *PageSpeed) error

	pageSpeedQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	pageSpeedType                 = reflect.TypeOf(&PageSpeed{})
	pageSpeedMapping              = queries.MakeStructMapping(pageSpeedType)
	pageSpeedPrimaryKeyMapping, _ = queries.BindMapping(pageSpeedType, pageSpeedMapping, pageSpeedPrimaryKeyColumns)
	pageSpeedInsertCacheMut       sync.RWMutex
	pageSpeedInsertCache          = make(map[string]insertCache)
	pageSpeedUpdateCacheMut       sync.RWMutex
	pageSpeedUpdateCache          = make(map[string]updateCache)
	pageSpeedUpsertCacheMut       sync.RWMutex
	pageSpeedUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var pageSpeedAfterSelectHooks []PageSpeedHook

var pageSpeedBeforeInsertHooks []PageSpeedHook
var pageSpeedAfterInsertHooks []PageSpeedHook

var pageSpeedBeforeUpdateHooks []PageSpeedHook
var pageSpeedAfterUpdateHooks []PageSpeedHook

var pageSpeedBeforeDeleteHooks []PageSpeedHook
var pageSpeedAfterDeleteHooks []PageSpeedHook

var pageSpeedBeforeUpsertHooks []PageSpeedHook
var pageSpeedAfterUpsertHooks []PageSpeedHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PageSpeed) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pageSpeedAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PageSpeed) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pageSpeedBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PageSpeed) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pageSpeedAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PageSpeed) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pageSpeedBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PageSpeed) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pageSpeedAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PageSpeed) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pageSpeedBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PageSpeed) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pageSpeedAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PageSpeed) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pageSpeedBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PageSpeed) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range pageSpeedAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPageSpeedHook registers your hook function for all future operations.
func AddPageSpeedHook(hookPoint boil.HookPoint, pageSpeedHook PageSpeedHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		pageSpeedAfterSelectHooks = append(pageSpeedAfterSelectHooks, pageSpeedHook)
	case boil.BeforeInsertHook:
		pageSpeedBeforeInsertHooks = append(pageSpeedBeforeInsertHooks, pageSpeedHook)
	case boil.AfterInsertHook:
		pageSpeedAfterInsertHooks = append(pageSpeedAfterInsertHooks, pageSpeedHook)
	case boil.BeforeUpdateHook:
		pageSpeedBeforeUpdateHooks = append(pageSpeedBeforeUpdateHooks, pageSpeedHook)
	case boil.AfterUpdateHook:
		pageSpeedAfterUpdateHooks = append(pageSpeedAfterUpdateHooks, pageSpeedHook)
	case boil.BeforeDeleteHook:
		pageSpeedBeforeDeleteHooks = append(pageSpeedBeforeDeleteHooks, pageSpeedHook)
	case boil.AfterDeleteHook:
		pageSpeedAfterDeleteHooks = append(pageSpeedAfterDeleteHooks, pageSpeedHook)
	case boil.BeforeUpsertHook:
		pageSpeedBeforeUpsertHooks = append(pageSpeedBeforeUpsertHooks, pageSpeedHook)
	case boil.AfterUpsertHook:
		pageSpeedAfterUpsertHooks = append(pageSpeedAfterUpsertHooks, pageSpeedHook)
	}
}

// One returns a single pageSpeed record from the query.
func (q pageSpeedQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PageSpeed, error) {
	o := &PageSpeed{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for page_speeds")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PageSpeed records from the query.
func (q pageSpeedQuery) All(ctx context.Context, exec boil.ContextExecutor) (PageSpeedSlice, error) {
	var o []*PageSpeed

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PageSpeed slice")
	}

	if len(pageSpeedAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PageSpeed records in the query.
func (q pageSpeedQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count page_speeds rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q pageSpeedQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if page_speeds exists")
	}

	return count > 0, nil
}

// PagespeedPageSpeedsStats retrieves all the page_speeds_stat's PageSpeedsStats with an executor via pagespeed_id column.
func (o *PageSpeed) PagespeedPageSpeedsStats(mods ...qm.QueryMod) pageSpeedsStatQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"page_speeds_stats\".\"pagespeed_id\"=?", o.ID),
	)

	return PageSpeedsStats(queryMods...)
}

// LoadPagespeedPageSpeedsStats allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (pageSpeedL) LoadPagespeedPageSpeedsStats(ctx context.Context, e boil.ContextExecutor, singular bool, maybePageSpeed interface{}, mods queries.Applicator) error {
	var slice []*PageSpeed
	var object *PageSpeed

	if singular {
		var ok bool
		object, ok = maybePageSpeed.(*PageSpeed)
		if !ok {
			object = new(PageSpeed)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePageSpeed)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePageSpeed))
			}
		}
	} else {
		s, ok := maybePageSpeed.(*[]*PageSpeed)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePageSpeed)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePageSpeed))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &pageSpeedR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &pageSpeedR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`page_speeds_stats`),
		qm.WhereIn(`page_speeds_stats.pagespeed_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load page_speeds_stats")
	}

	var resultSlice []*PageSpeedsStat
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice page_speeds_stats")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on page_speeds_stats")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for page_speeds_stats")
	}

	if len(pageSpeedsStatAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.PagespeedPageSpeedsStats = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &pageSpeedsStatR{}
			}
			foreign.R.Pagespeed = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.PagespeedID {
				local.R.PagespeedPageSpeedsStats = append(local.R.PagespeedPageSpeedsStats, foreign)
				if foreign.R == nil {
					foreign.R = &pageSpeedsStatR{}
				}
				foreign.R.Pagespeed = local
				break
			}
		}
	}

	return nil
}

// AddPagespeedPageSpeedsStats adds the given related objects to the existing relationships
// of the page_speed, optionally inserting them as new records.
// Appends related to o.R.PagespeedPageSpeedsStats.
// Sets related.R.Pagespeed appropriately.
func (o *PageSpeed) AddPagespeedPageSpeedsStats(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*PageSpeedsStat) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.PagespeedID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"page_speeds_stats\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"pagespeed_id"}),
				strmangle.WhereClause("\"", "\"", 2, pageSpeedsStatPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.Time, rel.PagespeedID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.PagespeedID = o.ID
		}
	}

	if o.R == nil {
		o.R = &pageSpeedR{
			PagespeedPageSpeedsStats: related,
		}
	} else {
		o.R.PagespeedPageSpeedsStats = append(o.R.PagespeedPageSpeedsStats, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &pageSpeedsStatR{
				Pagespeed: o,
			}
		} else {
			rel.R.Pagespeed = o
		}
	}
	return nil
}

// PageSpeeds retrieves all the records using an executor.
func PageSpeeds(mods ...qm.QueryMod) pageSpeedQuery {
	mods = append(mods, qm.From("\"page_speeds\""), qmhelper.WhereIsNull("\"page_speeds\".\"deleted_at\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"page_speeds\".*"})
	}

	return pageSpeedQuery{q}
}

// FindPageSpeed retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPageSpeed(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*PageSpeed, error) {
	pageSpeedObj := &PageSpeed{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"page_speeds\" where \"id\"=$1 and \"deleted_at\" is null", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, pageSpeedObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from page_speeds")
	}

	if err = pageSpeedObj.doAfterSelectHooks(ctx, exec); err != nil {
		return pageSpeedObj, err
	}

	return pageSpeedObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PageSpeed) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no page_speeds provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(pageSpeedColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	pageSpeedInsertCacheMut.RLock()
	cache, cached := pageSpeedInsertCache[key]
	pageSpeedInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			pageSpeedAllColumns,
			pageSpeedColumnsWithDefault,
			pageSpeedColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(pageSpeedType, pageSpeedMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(pageSpeedType, pageSpeedMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"page_speeds\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"page_speeds\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into page_speeds")
	}

	if !cached {
		pageSpeedInsertCacheMut.Lock()
		pageSpeedInsertCache[key] = cache
		pageSpeedInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PageSpeed.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PageSpeed) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	pageSpeedUpdateCacheMut.RLock()
	cache, cached := pageSpeedUpdateCache[key]
	pageSpeedUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			pageSpeedAllColumns,
			pageSpeedPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update page_speeds, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"page_speeds\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, pageSpeedPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(pageSpeedType, pageSpeedMapping, append(wl, pageSpeedPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update page_speeds row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for page_speeds")
	}

	if !cached {
		pageSpeedUpdateCacheMut.Lock()
		pageSpeedUpdateCache[key] = cache
		pageSpeedUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q pageSpeedQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for page_speeds")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for page_speeds")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PageSpeedSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), pageSpeedPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"page_speeds\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, pageSpeedPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in pageSpeed slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all pageSpeed")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PageSpeed) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no page_speeds provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(pageSpeedColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	pageSpeedUpsertCacheMut.RLock()
	cache, cached := pageSpeedUpsertCache[key]
	pageSpeedUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			pageSpeedAllColumns,
			pageSpeedColumnsWithDefault,
			pageSpeedColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			pageSpeedAllColumns,
			pageSpeedPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert page_speeds, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(pageSpeedPrimaryKeyColumns))
			copy(conflict, pageSpeedPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"page_speeds\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(pageSpeedType, pageSpeedMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(pageSpeedType, pageSpeedMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert page_speeds")
	}

	if !cached {
		pageSpeedUpsertCacheMut.Lock()
		pageSpeedUpsertCache[key] = cache
		pageSpeedUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PageSpeed record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PageSpeed) Delete(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PageSpeed provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), pageSpeedPrimaryKeyMapping)
		sql = "DELETE FROM \"page_speeds\" WHERE \"id\"=$1"
	} else {
		currTime := time.Now().In(boil.GetLocation())
		o.DeletedAt = null.TimeFrom(currTime)
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"page_speeds\" SET %s WHERE \"id\"=$2",
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		valueMapping, err := queries.BindMapping(pageSpeedType, pageSpeedMapping, append(wl, pageSpeedPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), valueMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from page_speeds")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for page_speeds")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q pageSpeedQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no pageSpeedQuery provided for delete all")
	}

	if hardDelete {
		queries.SetDelete(q.Query)
	} else {
		currTime := time.Now().In(boil.GetLocation())
		queries.SetUpdate(q.Query, M{"deleted_at": currTime})
	}

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from page_speeds")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for page_speeds")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PageSpeedSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(pageSpeedBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), pageSpeedPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
		}
		sql = "DELETE FROM \"page_speeds\" WHERE " +
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, pageSpeedPrimaryKeyColumns, len(o))
	} else {
		currTime := time.Now().In(boil.GetLocation())
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), pageSpeedPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
			obj.DeletedAt = null.TimeFrom(currTime)
		}
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"page_speeds\" SET %s WHERE "+
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 2, pageSpeedPrimaryKeyColumns, len(o)),
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		args = append([]interface{}{currTime}, args...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from pageSpeed slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for page_speeds")
	}

	if len(pageSpeedAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PageSpeed) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPageSpeed(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PageSpeedSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PageSpeedSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), pageSpeedPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"page_speeds\".* FROM \"page_speeds\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, pageSpeedPrimaryKeyColumns, len(*o)) +
		"and \"deleted_at\" is null"

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PageSpeedSlice")
	}

	*o = slice

	return nil
}

// PageSpeedExists checks if the PageSpeed row exists.
func PageSpeedExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"page_speeds\" where \"id\"=$1 and \"deleted_at\" is null limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if page_speeds exists")
	}

	return exists, nil
}

// Exists checks if the PageSpeed row exists.
func (o *PageSpeed) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PageSpeedExists(ctx, exec, o.ID)
}
